package ru.ea42.EaLogger;

import com.sun.net.httpserver.HttpExchange;

import java.util.Map;

public class HandlerList extends HttpHandlerBased {
    protected String doPost(HttpExchange exchange, Map params, String body) {
        return "";
    }

    protected String doGet(HttpExchange exchange, Map params) {
        String strRet = "<html>\r\n<head>\r\n  <meta charset=\"utf-8\">\r\n<title>EaLogger система</title>\r\n"
                + "<style>table {border-collapse: collapse;}\r\n "
                + "td, th {padding: 5px; border: 1px solid #98bf21;}</style>\r\n "
                + "</head>\r\n <body>\r\n<p>" + App.AppVersion + "</p>\r\n <p>Апи: <a href=\"/api01\">localhost:7878/api01</a></p>\r\n";
        // разделитель
        strRet = strRet + "<hr>\r\n";

        // последние 40 собщений лога
        strRet = strRet + "<table>\r\n <caption>Лог (последние 40 строк)</caption>\r\n <tr>\r\n <th>times</th> <th>level</th> <th>sys</th> <th>computer</th> <th>user</th> <th>id</th> <th>mess</th> </tr>\r\n";
        Qu qu = App.QuMan.getQu("SELECT * FROM log ORDER BY times DESC LIMIT 40");
        while (qu.getNext()) {
            strRet = strRet + "<tr>\r\n <td>" + qu.asString("times") + "</td><td>" + qu.asString("level") + "</td><td>"
                    + qu.asString("sys") + "</td><td>" + qu.asString("computer") + "</td><td>" + qu.asString("user")
                    + "</td><td>" + qu.asString("id") + "</td><td>" + qu.asString("mess") + "<td>\r\n </tr>\r\n";
        }
        qu.release();
        strRet = strRet + "</table><hr>\r\n";

        // текст АПИ
        strRet = strRet + App.QuMan.getHelp() + "<hr>\r\n";
        strRet = strRet + "</body>\r\n</html>";
        return strRet;
    }

    String txtApi = "<div class=WordSection1>\r\n" + "<p class=MsoNormal><o:p>&nbsp;</o:p></p>\r\n" + "\r\n"
            + "<p class=MsoNormal><o:p>&nbsp;</o:p></p>\r\n" + "\r\n" + "<p class=MsoNormal><o:p>&nbsp;</o:p></p>\r\n"
            + "\r\n" + "\r\n" + "<p class=MsoNormal> SED api01 сервера v2.19 <o:p></o:p></p>\r\n" + "\r\n"
            + "<p class=MsoNormal> Предназначен для простого взаимодействия между различными\r\n"
            + "системами.<o:p></o:p></p>\r\n" + "\r\n"
            + "<p class=MsoNormal>//====================================================================================================<o:p></o:p></p>\r\n"
            + "\r\n" + "<p class=MsoNormal><o:p>&nbsp;</o:p></p>\r\n" + "\r\n"
            + "<p class=MsoNormal><span style='mso-spacerun:yes'>    </span>§1 Общие\r\n"
            + "положения.<o:p></o:p></p>\r\n" + "\r\n"
            + "<p class=MsoNormal>//====================================================================================================<o:p></o:p></p>\r\n"
            + "\r\n" + "<p class=MsoNormal><o:p>&nbsp;</o:p></p>\r\n" + "\r\n"
            + "<p class=MsoNormal>1. Различные системы взаимодействуют с сервером SED\r\n"
            + "посредством HTTP запросов POST по единому URL. <o:p></o:p></p>\r\n" + "\r\n"
            + "<p class=MsoNormal>2. Запрос и ответ - JSON объекты. Кодировка UTF-8.<o:p></o:p></p>\r\n" + "\r\n"
            + "<p class=MsoNormal>3. Первое поле запроса &quot;<span class=SpellE>Toкen</span>&quot;\r\n"
            + "- <span class=SpellE>токен</span> доступа. По нему сервер SED определяет\r\n"
            + "сессию, уровень доступа. Может отсутствовать.<o:p></o:p></p>\r\n" + "\r\n"
            + "<p class=MsoNormal>4. Каждый JSON объект имеет обязательное поле &quot;<span\r\n"
            + "class=SpellE>Type</span>&quot;, содержащее строку. <o:p></o:p></p>\r\n" + "\r\n"
            + "<p class=MsoNormal>5. По содержимому поле &quot;<span class=SpellE>Type</span>&quot;\r\n"
            + "происходит дальнейшая разборка и обработка объекта.<o:p></o:p></p>\r\n" + "\r\n"
            + "<p class=MsoNormal><o:p>&nbsp;</o:p></p>\r\n" + "\r\n"
            + "<p class=MsoNormal>//====================================================================================================<o:p></o:p></p>\r\n"
            + "\r\n" + "<p class=MsoNormal>Стандартные ответы:<o:p></o:p></p>\r\n" + "\r\n"
            + "<p class=MsoNormal><o:p>&nbsp;</o:p></p>\r\n" + "\r\n"
            + "<p class=MsoNormal>Ответ с простой ошибкой. (Может прийти на любой запрос):<o:p></o:p></p>\r\n" + "\r\n"
            + "<p class=MsoNormal><span lang=EN-US style='mso-ansi-language:EN-US'>{<o:p></o:p></span></p>\r\n" + "\r\n"
            + "<p class=MsoNormal><span lang=EN-US style='mso-ansi-language:EN-US'><span\r\n"
            + "style='mso-spacerun:yes'>  </span>&quot;Type&quot;: &quot;Error&quot;,<o:p></o:p></span></p>\r\n"
            + "\r\n" + "<p class=MsoNormal><span lang=EN-US style='mso-ansi-language:EN-US'><span\r\n"
            + "style='mso-spacerun:yes'>  </span>&quot;Num&quot;: &quot;558775&quot; <span\r\n"
            + "style='mso-tab-count:4'>                                                         </span>-\r\n"
            + "</span>номер<span style='mso-ansi-language:EN-US'> </span>ошибки<span\r\n"
            + "lang=EN-US style='mso-ansi-language:EN-US'> 6 </span>цифр<span lang=EN-US\r\n"
            + "style='mso-ansi-language:EN-US'>. </span>По номеру можно выполнить перевод на\r\n"
            + "другие языки<o:p></o:p></p>\r\n" + "\r\n"
            + "<p class=MsoNormal><span style='mso-spacerun:yes'>  </span>&quot;<span\r\n"
            + "class=SpellE>Mess</span>&quot;: &quot;<span class=SpellE>site</span> <span\r\n"
            + "class=SpellE>not</span> <span class=SpellE>aviable</span>&quot; <span\r\n"
            + "style='mso-tab-count:1'>        </span>- общее описание ошибки <span\r\n"
            + "class=GramE>по <span class=SpellE>английски</span></span><o:p></o:p></p>\r\n" + "\r\n"
            + "<p class=MsoNormal><span style='mso-spacerun:yes'>  </span>&quot;<span\r\n"
            + "class=SpellE>Data</span>&quot;: &quot;8080&quot; <span style='mso-tab-count:\r\n"
            + "4'>                                                              </span>-\r\n"
            + "произвольное дополнительное содержимое, через запятую, для подстановки в <span\r\n"
            + "class=SpellE>Mess</span>, <span class=GramE>например</span> номер <span\r\n"
            + "class=SpellE>site</span><o:p></o:p></p>\r\n" + "\r\n" + "<p class=MsoNormal>}<o:p></o:p></p>\r\n"
            + "\r\n" + "<p class=MsoNormal><o:p>&nbsp;</o:p></p>\r\n" + "\r\n"
            + "<p class=MsoNormal>Пустой ответ - Всё <span class=SpellE>ок</span>:<o:p></o:p></p>\r\n" + "\r\n"
            + "<p class=MsoNormal>{&quot;<span class=SpellE>Type</span>&quot;: &quot;<span\r\n"
            + "class=SpellE>Ok</span>&quot;}<o:p></o:p></p>\r\n" + "\r\n"
            + "<p class=MsoNormal><o:p>&nbsp;</o:p></p>\r\n" + "\r\n" + "<p class=MsoNormal><o:p>&nbsp;</o:p></p>\r\n"
            + "\r\n" + "<p class=MsoNormal><span style='mso-spacerun:yes'>    </span>§2 Подключение<o:p></o:p></p>\r\n"
            + "\r\n" + "<p class=MsoNormal>Подключение к серверу SED, создание сессии на нём. Получение\r\n"
            + "<span class=SpellE>токена</span> доступа от сессии. <o:p></o:p></p>\r\n" + "\r\n"
            + "<p class=MsoNormal>Сессия автоматически закрывается через 10 минут после\r\n"
            + "последнего запроса к ней.<o:p></o:p></p>\r\n" + "\r\n"
            + "<p class=MsoNormal>//====================================================================================================<o:p></o:p></p>\r\n"
            + "\r\n"
            + "<p class=MsoNormal>Запросить <span class=SpellE>токен</span> доступа / сессию. <o:p></o:p></p>\r\n"
            + "\r\n" + "<p class=MsoNormal>Запрос:<o:p></o:p></p>\r\n" + "\r\n"
            + "<p class=MsoNormal><span lang=EN-US style='mso-ansi-language:EN-US'>{<o:p></o:p></span></p>\r\n" + "\r\n"
            + "<p class=MsoNormal><span lang=EN-US style='mso-ansi-language:EN-US'><span\r\n"
            + "style='mso-spacerun:yes'>  </span>&quot;Type&quot;: &quot;quAuth&quot;, <o:p></o:p></span></p>\r\n"
            + "\r\n" + "<p class=MsoNormal><span lang=EN-US style='mso-ansi-language:EN-US'><span\r\n"
            + "style='mso-spacerun:yes'>  </span>&quot;Data&quot;: {<o:p></o:p></span></p>\r\n" + "\r\n"
            + "<p class=MsoNormal><span lang=EN-US style='mso-ansi-language:EN-US'><span\r\n"
            + "style='mso-tab-count:1'>                </span>&quot;Login&quot;: &quot;&lt;</span><span\r\n"
            + "class=SpellE>ЗначениеЛогина</span><span lang=EN-US style='mso-ansi-language:\r\n"
            + "EN-US'>&gt;&quot;,<o:p></o:p></span></p>\r\n" + "\r\n"
            + "<p class=MsoNormal><span lang=EN-US style='mso-ansi-language:EN-US'><span\r\n"
            + "style='mso-tab-count:1'>                </span>&quot;Password&quot;: &quot;&lt;</span><span\r\n"
            + "class=SpellE>ЗначениеПароля</span><span lang=EN-US style='mso-ansi-language:\r\n"
            + "EN-US'>&gt;&quot;<o:p></o:p></span></p>\r\n" + "\r\n"
            + "<p class=MsoNormal><span lang=EN-US style='mso-ansi-language:EN-US'><span\r\n"
            + "style='mso-spacerun:yes'>  </span>}<o:p></o:p></span></p>\r\n" + "\r\n"
            + "<p class=MsoNormal><span lang=EN-US style='mso-ansi-language:EN-US'>}<o:p></o:p></span></p>\r\n" + "\r\n"
            + "<p class=MsoNormal><span lang=EN-US style='mso-ansi-language:EN-US'><o:p>&nbsp;</o:p></span></p>\r\n"
            + "\r\n"
            + "<p class=MsoNormal>Ответ<span lang=EN-US style='mso-ansi-language:EN-US'>:<o:p></o:p></span></p>\r\n"
            + "\r\n" + "<p class=MsoNormal><span lang=EN-US style='mso-ansi-language:EN-US'>{<o:p></o:p></span></p>\r\n"
            + "\r\n" + "<p class=MsoNormal><span lang=EN-US style='mso-ansi-language:EN-US'><span\r\n"
            + "style='mso-spacerun:yes'>  </span>&quot;Type&quot;: &quot;reAuth&quot;, <o:p></o:p></span></p>\r\n"
            + "\r\n" + "<p class=MsoNormal><span lang=EN-US style='mso-ansi-language:EN-US'><span\r\n"
            + "style='mso-spacerun:yes'>  </span></span>&quot;<span class=SpellE>Data</span>&quot;:\r\n"
            + "&quot;&lt;<span class=SpellE>ЗначениеТокена</span>&gt;&quot;<o:p></o:p></p>\r\n" + "\r\n"
            + "<p class=MsoNormal>}<o:p></o:p></p>\r\n" + "\r\n"
            + "<p class=MsoNormal>Если &lt;<span class=SpellE>ЗначениеТокена</span>&gt; пустая\r\n"
            + "строка, то не верные логин / пароль. <o:p></o:p></p>\r\n" + "\r\n"
            + "<p class=MsoNormal><o:p>&nbsp;</o:p></p>\r\n" + "\r\n" + "<p class=MsoNormal><o:p>&nbsp;</o:p></p>\r\n"
            + "\r\n" + "<p class=MsoNormal><span style='mso-spacerun:yes'>    </span>§3 Запросы на\r\n"
            + "прием / передачу сообщений <o:p></o:p></p>\r\n" + "\r\n"
            + "<p class=MsoNormal>Подключаемся к серверу SED. Запрашиваем сообщения, пока не\r\n"
            + "заберем все. Обрабатываем каждое сообщение. <o:p></o:p></p>\r\n" + "\r\n"
            + "<p class=MsoNormal>Если сообщение нормально обработано, удаляем его на сервере\r\n"
            + "SED. Посылаем <span class=SpellE>небходимые</span> сообщения <o:p></o:p></p>\r\n" + "\r\n"
            + "<p class=MsoNormal>другим системам. Спим.<o:p></o:p></p>\r\n" + "\r\n"
            + "<p class=MsoNormal>//====================================================================================================<o:p></o:p></p>\r\n"
            + "\r\n" + "<p class=MsoNormal>Запросить очередное входящее сообщение процедуры. <o:p></o:p></p>\r\n"
            + "\r\n" + "<p class=MsoNormal>Запрос:<o:p></o:p></p>\r\n" + "\r\n"
            + "<p class=MsoNormal>{<o:p></o:p></p>\r\n" + "\r\n"
            + "<p class=MsoNormal><span style='mso-spacerun:yes'>  </span>&quot;<span\r\n"
            + "class=SpellE>Token</span>&quot;: &quot;&lt;<span class=SpellE>ЗначениеТокена</span>&gt;&quot;,\r\n"
            + "<o:p></o:p></p>\r\n" + "\r\n"
            + "<p class=MsoNormal><span style='mso-spacerun:yes'>  </span>&quot;<span\r\n"
            + "class=SpellE>Type</span>&quot;: &quot;<span class=SpellE>quMes</span>&quot;<o:p></o:p></p>\r\n" + "\r\n"
            + "<p class=MsoNormal>}<o:p></o:p></p>\r\n" + "\r\n" + "<p class=MsoNormal><o:p>&nbsp;</o:p></p>\r\n"
            + "\r\n" + "<p class=MsoNormal>Ответы стандартные или очередное сообщение. <o:p></o:p></p>\r\n" + "\r\n"
            + "<p class=MsoNormal>Ответ:<o:p></o:p></p>\r\n" + "\r\n" + "<p class=MsoNormal>{<o:p></o:p></p>\r\n"
            + "\r\n" + "<p class=MsoNormal><span style='mso-spacerun:yes'>  </span>&quot;<span\r\n"
            + "class=SpellE>Type</span>&quot;: &quot;<span class=SpellE>reMes</span>&quot;,<o:p></o:p></p>\r\n" + "\r\n"
            + "<p class=MsoNormal><span style='mso-spacerun:yes'>  </span>&quot;<span\r\n"
            + "class=SpellE>FromNode</span>&quot;: &quot;205&quot;, <span style='mso-tab-count:\r\n"
            + "5'>                                                                  </span>-\r\n"
            + "уникальный номер системы в SED, от кого пришло сообщение<o:p></o:p></p>\r\n" + "\r\n"
            + "<p class=MsoNormal><span style='mso-spacerun:yes'>  </span>&quot;<span\r\n"
            + "class=SpellE>Id</span>&quot;: &quot;80182018-0905-1530000304<span class=GramE>&quot;,<span\r\n"
            + "style='mso-tab-count:2'>                      </span></span>- <span\r\n"
            + "class=SpellE>гуид</span> сообщения<o:p></o:p></p>\r\n" + "\r\n"
            + "<p class=MsoNormal><span style='mso-spacerun:yes'>  </span>&quot;<span\r\n"
            + "class=SpellE>Data</span>&quot;: {...}<span style='mso-tab-count:7'>                                                                                                    </span>-\r\n"
            + "JSON объект с сообщением<o:p></o:p></p>\r\n" + "\r\n" + "<p class=MsoNormal>}<o:p></o:p></p>\r\n"
            + "\r\n" + "<p class=MsoNormal>Если ответ типа Ок - значит нет сообщений для получения.<o:p></o:p></p>\r\n"
            + "\r\n" + "<p class=MsoNormal><o:p>&nbsp;</o:p></p>\r\n" + "\r\n"
            + "<p class=MsoNormal>Удалить очередное принятое сообщение из очереди. <o:p></o:p></p>\r\n" + "\r\n"
            + "<p class=MsoNormal>Запрос:<o:p></o:p></p>\r\n" + "\r\n" + "<p class=MsoNormal>{<o:p></o:p></p>\r\n"
            + "\r\n" + "<p class=MsoNormal><span style='mso-spacerun:yes'>  </span>&quot;<span\r\n"
            + "class=SpellE>Token</span>&quot;: &quot;&lt;<span class=SpellE>ЗначениеТокена</span>&gt;&quot;,<o:p></o:p></p>\r\n"
            + "\r\n" + "<p class=MsoNormal><span style='mso-spacerun:yes'>  </span>&quot;<span\r\n"
            + "class=SpellE>Type</span>&quot;: &quot;<span class=SpellE>delMes</span>&quot;,<o:p></o:p></p>\r\n"
            + "\r\n" + "<p class=MsoNormal><span style='mso-spacerun:yes'>  </span>&quot;<span\r\n"
            + "class=SpellE>Id</span>&quot;: &quot;80182018-0905-1530000304&quot;<span\r\n"
            + "style='mso-tab-count:2'>                       </span>- <span class=SpellE>гуид</span>\r\n"
            + "сообщения<o:p></o:p></p>\r\n" + "\r\n" + "<p class=MsoNormal>}<o:p></o:p></p>\r\n" + "\r\n"
            + "<p class=MsoNormal><o:p>&nbsp;</o:p></p>\r\n" + "\r\n"
            + "<p class=MsoNormal>Ответы стандартные.<o:p></o:p></p>\r\n" + "\r\n"
            + "<p class=MsoNormal><o:p>&nbsp;</o:p></p>\r\n" + "\r\n"
            + "<p class=MsoNormal>//====================================================================================================<o:p></o:p></p>\r\n"
            + "\r\n" + "<p class=MsoNormal>Послать сообщение.<o:p></o:p></p>\r\n" + "\r\n"
            + "<p class=MsoNormal>Запрос:<o:p></o:p></p>\r\n" + "\r\n" + "<p class=MsoNormal>{<o:p></o:p></p>\r\n"
            + "\r\n" + "<p class=MsoNormal><span style='mso-spacerun:yes'>  </span>&quot;<span\r\n"
            + "class=SpellE>Token</span>&quot;: &quot;&lt;<span class=SpellE>ЗначениеТокена</span>&gt;&quot;,<o:p></o:p></p>\r\n"
            + "\r\n" + "<p class=MsoNormal><span style='mso-spacerun:yes'>  </span>&quot;<span\r\n"
            + "class=SpellE>Type</span>&quot;: &quot;<span class=SpellE>quPostMes</span>&quot;,\r\n"
            + "<o:p></o:p></p>\r\n" + "\r\n"
            + "<p class=MsoNormal><span style='mso-spacerun:yes'>  </span>&quot;<span\r\n"
            + "class=SpellE>Node</span>&quot;: &quot;20578&quot;, <span style='mso-tab-count:\r\n"
            + "5'>                                                                        </span>-\r\n"
            + "уникальный номер системы в SED, кому отравить сообщение<o:p></o:p></p>\r\n" + "\r\n"
            + "<p class=MsoNormal><span style='mso-spacerun:yes'>  </span>&quot;<span\r\n"
            + "class=SpellE>Data</span>&quot;: {...}<span style='mso-tab-count:6'>                                                                                     </span>-\r\n"
            + "JSON объект с сообщением<o:p></o:p></p>\r\n" + "\r\n" + "<p class=MsoNormal>}<o:p></o:p></p>\r\n"
            + "\r\n" + "<p class=MsoNormal><o:p>&nbsp;</o:p></p>\r\n" + "\r\n"
            + "<p class=MsoNormal>Ответы стандартные.<o:p></o:p></p>\r\n" + "\r\n"
            + "<p class=MsoNormal><o:p>&nbsp;</o:p></p>\r\n" + "\r\n" + "<p class=MsoNormal><o:p>&nbsp;</o:p></p>\r\n"
            + "\r\n" + "<p class=MsoNormal><span style='mso-spacerun:yes'>    </span>§4 Вспомогательные\r\n"
            + "запросы<o:p></o:p></p>\r\n" + "\r\n"
            + "<p class=MsoNormal>//====================================================================================================<o:p></o:p></p>\r\n"
            + "\r\n" + "<p class=MsoNormal>Запросить версию SED.<o:p></o:p></p>\r\n" + "\r\n"
            + "<p class=MsoNormal>Запрос<span lang=EN-US style='mso-ansi-language:EN-US'>:<o:p></o:p></span></p>\r\n"
            + "\r\n" + "<p class=MsoNormal><span lang=EN-US style='mso-ansi-language:EN-US'>{&quot;Type&quot;:\r\n"
            + "&quot;Version&quot;}<o:p></o:p></span></p>\r\n" + "\r\n"
            + "<p class=MsoNormal><span lang=EN-US style='mso-ansi-language:EN-US'><o:p>&nbsp;</o:p></span></p>\r\n"
            + "\r\n"
            + "<p class=MsoNormal>Ответ<span lang=EN-US style='mso-ansi-language:EN-US'>:<o:p></o:p></span></p>\r\n"
            + "\r\n" + "<p class=MsoNormal><span lang=EN-US style='mso-ansi-language:EN-US'>{<o:p></o:p></span></p>\r\n"
            + "\r\n" + "<p class=MsoNormal><span lang=EN-US style='mso-ansi-language:EN-US'><span\r\n"
            + "style='mso-spacerun:yes'>  </span>&quot;Type&quot;: &quot;API&quot;, <o:p></o:p></span></p>\r\n" + "\r\n"
            + "<p class=MsoNormal><span lang=EN-US style='mso-ansi-language:EN-US'><span\r\n"
            + "style='mso-spacerun:yes'>  </span></span>&quot;<span class=SpellE>Data</span>&quot;:\r\n"
            + "&quot;api01&quot; <span style='mso-tab-count:2'>                             </span>-\r\n"
            + "строка, версия АПИ<o:p></o:p></p>\r\n" + "\r\n" + "<p class=MsoNormal>}<o:p></o:p></p>\r\n" + "\r\n"
            + "<p class=MsoNormal><o:p>&nbsp;</o:p></p>\r\n" + "\r\n"
            + "<p class=MsoNormal>//====================================================================================================<o:p></o:p></p>\r\n"
            + "\r\n" + "<p class=MsoNormal>Запросить значение по ключу, без авторизации. Ответ берется\r\n"
            + "из общей базы сервера без привязки к логину. <o:p></o:p></p>\r\n" + "\r\n"
            + "<p class=MsoNormal>Запрос:<o:p></o:p></p>\r\n" + "\r\n" + "<p class=MsoNormal>{<o:p></o:p></p>\r\n"
            + "\r\n" + "<p class=MsoNormal><span style='mso-spacerun:yes'>  </span>&quot;<span\r\n"
            + "class=SpellE>Type</span>&quot;: &quot;<span class=SpellE>quVal</span>&quot;, <o:p></o:p></p>\r\n"
            + "\r\n" + "<p class=MsoNormal><span style='mso-spacerun:yes'>  </span>&quot;<span\r\n"
            + "class=SpellE>Data</span>&quot;: &quot;&lt;<span class=SpellE>ТелоКлюча</span>&gt;&quot;\r\n"
            + "<o:p></o:p></p>\r\n" + "\r\n" + "<p class=MsoNormal>}<o:p></o:p></p>\r\n" + "\r\n"
            + "<p class=MsoNormal><o:p>&nbsp;</o:p></p>\r\n" + "\r\n" + "<p class=MsoNormal>Ответ:<o:p></o:p></p>\r\n"
            + "\r\n" + "<p class=MsoNormal>{<o:p></o:p></p>\r\n" + "\r\n"
            + "<p class=MsoNormal><span style='mso-spacerun:yes'>  </span>&quot;<span\r\n"
            + "class=SpellE>Type</span>&quot;: &quot;<span class=SpellE>reVal</span>&quot;, <o:p></o:p></p>\r\n"
            + "\r\n" + "<p class=MsoNormal><span style='mso-spacerun:yes'>  </span>&quot;<span\r\n"
            + "class=SpellE>Data</span>&quot;: &quot;&lt;<span class=SpellE>ТелоЗначения</span>&gt;&quot;<o:p></o:p></p>\r\n"
            + "\r\n" + "<p class=MsoNormal>}<o:p></o:p></p>\r\n" + "\r\n"
            + "<p class=MsoNormal>Если ответ пустая строка, то запрашиваемого ключ <span\r\n"
            + "class=SpellE>отсутсвует</span> в базе. <o:p></o:p></p>\r\n" + "\r\n"
            + "<p class=MsoNormal><o:p>&nbsp;</o:p></p>\r\n" + "\r\n"
            + "<p class=MsoNormal>//====================================================================================================<o:p></o:p></p>\r\n"
            + "\r\n" + "<p class=MsoNormal><span class=SpellE>Логировать</span> в SED.<o:p></o:p></p>\r\n" + "\r\n"
            + "<p class=MsoNormal>Запрос:<o:p></o:p></p>\r\n" + "\r\n" + "<p class=MsoNormal>{<o:p></o:p></p>\r\n"
            + "\r\n" + "<p class=MsoNormal><span style='mso-spacerun:yes'>  </span>&quot;<span\r\n"
            + "class=SpellE>Type</span>&quot;: &quot;<span class=SpellE>quLog</span>&quot;, <o:p></o:p></p>\r\n"
            + "\r\n" + "<p class=MsoNormal><span style='mso-spacerun:yes'>  </span>&quot;<span\r\n"
            + "class=SpellE>Level</span>&quot;: 2, <span style='mso-tab-count:6'>                                                                                      </span>-\r\n"
            + "уровень: 0 - ошибка, 1 - предупреждение, 2 - инфо, 3 - замечание, 4 - дебаг1, 5\r\n"
            + "- дебаг2<o:p></o:p></p>\r\n" + "\r\n"
            + "<p class=MsoNormal><span style='mso-spacerun:yes'>  </span>&quot;<span\r\n"
            + "class=SpellE>Sys</span>&quot;: &quot;1<span class=GramE>С:ОУП</span>&quot;, <span\r\n"
            + "style='mso-tab-count:5'>                                                                         </span>-\r\n"
            + "имя системы<o:p></o:p></p>\r\n" + "\r\n"
            + "<p class=MsoNormal><span style='mso-spacerun:yes'>  </span>&quot;<span\r\n"
            + "class=SpellE>Computer</span>&quot;: &quot;serv-006&quot;, <span\r\n"
            + "style='mso-tab-count:3'>                                         </span>- имя <span\r\n"
            + "class=SpellE>компьтера</span><o:p></o:p></p>\r\n" + "\r\n"
            + "<p class=MsoNormal><span style='mso-spacerun:yes'>  </span>&quot;<span\r\n"
            + "class=SpellE>User</span>&quot;: &quot;<span class=SpellE>evt_a</span>&quot;, <span\r\n"
            + "style='mso-tab-count:5'>                                                                          </span>-\r\n"
            + "имя пользователя<o:p></o:p></p>\r\n" + "\r\n"
            + "<p class=MsoNormal><span style='mso-spacerun:yes'>  </span>&quot;<span\r\n"
            + "class=SpellE>Id</span>&quot;: &quot;80182018-0905-1530000304<span class=GramE>&quot;,<span\r\n"
            + "style='mso-tab-count:1'>      </span></span>- ид чего-то, вспомогательное, для\r\n"
            + "ориентировки.<o:p></o:p></p>\r\n" + "\r\n"
            + "<p class=MsoNormal><span style='mso-spacerun:yes'>  </span>&quot;<span\r\n"
            + "class=SpellE>Mess</span>&quot;: &quot;Всё ОК!!!!!&quot;<span style='mso-tab-count:\r\n"
            + "1'> </span> <span style='mso-tab-count:3'>                                              </span>-\r\n"
            + "сообщение<o:p></o:p></p>\r\n" + "\r\n" + "<p class=MsoNormal>}<o:p></o:p></p>\r\n" + "\r\n"
            + "<p class=MsoNormal><o:p>&nbsp;</o:p></p>\r\n" + "\r\n"
            + "<p class=MsoNormal>Ответ всегда Ок.<o:p></o:p></p>\r\n" + "\r\n"
            + "<p class=MsoNormal><o:p>&nbsp;</o:p></p>\r\n" + "\r\n"
            + "<p class=MsoNormal>//====================================================================================================</p>\r\n"
            + "\r\n" + "</div>";
}